# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: L:/CPU54/CPU54.srcs/sources_1/ip/dist_iram_ip/dist_iram_ip.xci
# IP: The module: 'dist_iram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: l:/CPU54/CPU54.srcs/sources_1/ip/dist_iram_ip/dist_iram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_iram_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: L:/CPU54/CPU54.srcs/sources_1/ip/dist_iram_ip/dist_iram_ip.xci
# IP: The module: 'dist_iram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: l:/CPU54/CPU54.srcs/sources_1/ip/dist_iram_ip/dist_iram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_iram_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
