# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir L:/CPU54/CPU54.cache/wt [current_project]
set_property parent.project_path L:/CPU54/CPU54.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo l:/CPU54/CPU54.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files L:/CPU31_COE/RL_INSTR.coe
add_files L:/CPU31_COE/RL_Data.coe
add_files L:/CPU31_COE/RL_Data6.coe
add_files -quiet l:/CPU54/CPU54.srcs/sources_1/ip/dist_dmem_ip/dist_dmem_ip.dcp
set_property used_in_implementation false [get_files l:/CPU54/CPU54.srcs/sources_1/ip/dist_dmem_ip/dist_dmem_ip.dcp]
add_files -quiet l:/CPU54/CPU54.srcs/sources_1/ip/dist_iram_ip/dist_iram_ip.dcp
set_property used_in_implementation false [get_files l:/CPU54/CPU54.srcs/sources_1/ip/dist_iram_ip/dist_iram_ip.dcp]
read_verilog -library xil_defaultlib {
  L:/CPU54/CPU54.srcs/sources_1/new/VGA_Color.v
  L:/CPU54/CPU54.srcs/sources_1/new/VGA_640x480.v
  L:/CPU54/CPU54.srcs/sources_1/new/Regfiles.v
  L:/CPU54/CPU54.srcs/sources_1/new/DIVU.v
  L:/CPU54/CPU54.srcs/sources_1/new/DIV.v
  L:/CPU54/CPU54.srcs/sources_1/new/CP0.v
  L:/CPU54/CPU54.srcs/sources_1/new/CONTROL.v
  L:/CPU54/CPU54.srcs/sources_1/new/CLZ.v
  L:/CPU54/CPU54.srcs/sources_1/new/alu.v
  L:/CPU54/CPU54.srcs/sources_1/new/vga.v
  L:/CPU54/CPU54.srcs/sources_1/new/CPU54.v
  L:/CPU54/CPU54.srcs/sources_1/new/io_sel.v
  L:/CPU54/CPU54.srcs/sources_1/new/sscomp_dataflow.v
}
read_ip -quiet L:/CPU54/CPU54.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all l:/CPU54/CPU54.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all l:/CPU54/CPU54.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all l:/CPU54/CPU54.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files L:/CPU54/CPU54.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc L:/CPU54/CPU54.srcs/constrs_1/new/cpu.xdc
set_property used_in_implementation false [get_files L:/CPU54/CPU54.srcs/constrs_1/new/cpu.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
